### ISSUE TITLE
Failed to fetch sequence; Error with k-mer repeat count calculations; terminating program.

### ISSUE THREAD

**Issue by JessicaRoelands** [OSU-SRLab/MANTIS#54]
Hi,
Using MANTIS v1.0.4, I got the following error:
```
Getting repeat counts for repeat units (k-mers) ...
b'[W::fai_get_val] Reference chr1:10485-10499 not found in file, returning empty sequence\n[11/21/19 10:32:54] MANTIS K-Mer Repeat Counter\n[11/21/19 10:32:54] Loading target MSI loci from BED file ...\nTraceback (most recent call last):\n  File "MANTIS/v1.0.4/kmer_repeat_counter.py", line 859, in <module>\n    msi_loci = mll.load_loci(config[\'bedfile\'])\n  File "MANTIS/v1.0.4/kmer_repeat_counter.py", line 56, in load_loci\n    self.correct_off_by_one_errors(locus)                    \n  File "MANTIS/v1.0.4/kmer_repeat_counter.py", line 75, in correct_off_by_one_errors\n    raw_sequence = self.get_sequence(position)\n  File "MANTIS/v1.0.4/kmer_repeat_counter.py", line 106, in get_sequence\n    for subseq in pysam.faidx(self.genome_path, locus)[1:]:\n  File "MANTIS/v1.0.4/venv/lib/python3.6/site-packages/pysam/utils.py", line 75, in __call__\n    stderr))\npysam.utils.SamtoolsError: \'samtools returned with error 1: stdout=>chr1:10485-10499\\n, stderr=[faidx] Failed to fetch sequence in chr1:10485-10499\\n\'\n'
Error with k-mer repeat count calculations; terminating program.
```
The bed file that is used as input was created with RepeatFinder with reference genome hs37d5.fa.

Could you help to resolve this issue?

Thanks,

Jessica

**Comment by rbonneville** [comment]
Hello Jessica,

In your fasta file, are chromosomes listed as "chr1" or "1"?

**Comment by JessicaRoelands** [comment]
Chromosomes are listed as "1"

**Comment by rbonneville** [comment]
Try listing the chromosomes as "chr#" in the fasta and re-running. It looks like this is potentially a 1 vs. chr1 mismatch issue. Thank you, and please let us know if this does not resolve the issue or you have any additional difficulties.

**Comment by JessicaRoelands** [comment]
Thank you very much for this suggestion. It is working now!

**Comment by DrNeelChit** [comment]
Hi,
I too have the same issue...
how is it resolved..
