### ISSUE TITLE
Error with k-mer repeat count calculations; terminating program, which seems to be triggered by "_multiprocessing.SemLock Permission Denied"

### ISSUE THREAD

**Issue by HuangRuocheng** [OSU-SRLab/MANTIS#60]
Hello!

Sorry to bother you, and thanks for any response.

I am trying the latest version mantis v1.0.5 ( ps, which in its log shows v1.0.4 ), and came across the following error:

Mon Oct 18 12:21:13 CST 2021
Microsatellite Analysis for Normal-Tumor InStability (v1.0.4)
/home/dna/pipe_MSIsensor-pro/environments/envs/msisensor_v1/bin/python /home/dna/pipe_MSIsensor-pr
o/environments/sbin/MANTIS-1.0.5/kmer_repeat_counter.py \
-n /data01/huangrc/out/02_realign/NP01-B-Blood-wes.recalibrated.bam \
-t /data01/huangrc/out/02_realign/NP01-B-wes.recalibrated.bam \
-b /data01/huangrc/out_mantis2/01_reference/reference.bed \
-o /data01/huangrc/out_mantis2/02_msi/NP01-B-wes.mantis.kmer_counts.txt \
--min-read-quality 20.0 \
--min-locus-quality 25.0 \
--min-read-length 35 \
--genome /home/dna/data/gatk_resource_bundle/hg19/ucsc.hg19.fasta \
--threads 8 
Getting repeat counts for repeat units (k-mers) ...
b'/home/dna/pipe_MSIsensor-pro/environments/sbin/MANTIS-1.0.5/kmer_repeat_counter.py:149: SyntaxWarning: "is" with a literal. Did you mean "=="?\n  if (offset is 0) or read.seq[0:offset] == locus.kmer[offset:]:\n/home/dna/pipe_MSIsensor-pro/environments/sbin/MANTIS-1.0.5/kmer_repeat_counter.py:474: SyntaxWarning: "is" with a literal. Did you mean "=="?\n  if self.debug_output and (n % 10000 is 0):\n/home/dna/pipe_MSIsensor-pro/environments/sbin/MANTIS-1.0.5/kmer_repeat_counter.py:530: SyntaxWarning: "is" with a literal. Did you mean "=="?\n  if qsize is 0:\n/home/dna/pipe_MSIsensor-pro/environments/sbin/MANTIS-1.0.5/kmer_repeat_counter.py:612: SyntaxWarning: "is" with a literal. Did you mean "=="?\n  if loop_counter % proc_check_interval is 0:\n[10/18/21 12:21:18] MANTIS K-Mer Repeat Counter\n[10/18/21 12:21:18] Loading target MSI loci from BED file ...\n[10/18/21 13:29:55] Loaded 2993651 loci.\n[10/18/21 13:29:55] Processing normal input file with 8 thread(s) ...\nTraceback (most recent call last):\n  File "/home/dna/pipe_MSIsensor-pro/environments/sbin/MANTIS-1.0.5/kmer_repeat_counter.py", line 868, in <module>\n    normal = krc.process(config[\'normal_filepath\'], msi_loci, config)\n  File "/home/dna/pipe_MSIsensor-pro/environments/sbin/MANTIS-1.0.5/kmer_repeat_counter.py", line 560, in process\n    queue_out = Queue()\n  File "/home/dna/pipe_MSIsensor-pro/environments/envs/msisensor_v1/lib/python3.8/multiprocessing/context.py", line 103, in Queue\n    return Queue(maxsize, ctx=self.get_context())\n  File "/home/dna/pipe_MSIsensor-pro/environments/envs/msisensor_v1/lib/python3.8/multiprocessing/queues.py", line 42, in __init__\n    self._rlock = ctx.Lock()\n  File "/home/dna/pipe_MSIsensor-pro/environments/envs/msisensor_v1/lib/python3.8/multiprocessing/context.py", line 68, in Lock\n    return Lock(ctx=self.get_context())\n  File "/home/dna/pipe_MSIsensor-pro/environments/envs/msisensor_v1/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__\n    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)\n  File "/home/dna/pipe_MSIsensor-pro/environments/envs/msisensor_v1/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__\n    sl = self._semlock = _multiprocessing.SemLock(\nPermissionError: [Errno 13] Permission denied\n'
Error with k-mer repeat count calculations; terminating program.
Finishing mantis msi
Mon Oct 18 13:30:13 CST 2021

after running for 1 hour or so.

I found a similar thread in https://github.com/OSU-SRLab/MANTIS/issues/21, but it seems my error is a little different from it, and triggered by "_multiprocessing.SemLock Permission denied"

my python version is 3.8.0, pysam==v0.17.0, numpy==v1.21.2

And my server has /home/shm set to be 777. And several other BAMs have successfully got results in the same server.

ps, I am trying --threads 1 too

Looking forward to any response, and thanks very much!!

**Comment by HuangRuocheng** [comment]
I am very very sorry that it turns out one of my servers has /dev/shm set to be 600. After setting it to 777, the error is gone... I am so sorry to bother you!!!!
